Externalized Tool Versions
neoforged/NeoFormRuntime pull request #16
Opened 2024-06-23 18:02 UTC by shartte

Externalized and added to a new variant for MDG to pre-load tools.

2024-06-23 18:05 UTC, Matyrobbrt requested changes

2024-06-23 18:05 UTC, Matyrobbrt commented on src/main/java/net/neoforged/neoform/runtime/utils/ToolCoordinate.java
> +        try (var in = ToolCoordinate.class.getResourceAsStream("Tools.properties")) {
Please please please please please use lowercase `tools.properties`

Also, generally you use `/<file>`

2024-06-23 18:05 UTC, Matyrobbrt commented on src/main/java/net/neoforged/neoform/runtime/utils/ToolCoordinate.java
> +            throw new IllegalStateException("ToolVersions.properties failed to be read.", e);
You meant tools.properties, right?

2024-06-23 18:14 UTC, Technici4n commented on build.gradle
> +file("src/main/resources/net/neoforged/neoform/runtime/utils/Tools.properties").withInputStream {
notpick: why the capital `T`?

2024-06-25 16:19 UTC, Matyrobbrt approved these changes

2024-06-25 16:20 UTC, merged